# Generated by Django 5.2.11 on 2026-02-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début de la prescription.')),
                ('end_date', models.DateField(help_text='Date de fin de la prescription.')),
                ('status', models.CharField(choices=[('valide', 'Valide'), ('en_attente', 'En attente'), ('suppr', 'Supprimée')], default='en_attente', help_text='Statut de la prescription.', max_length=16)),
                ('comment', models.TextField(blank=True, default='', help_text='Commentaire optionnel sur la prescription.')),
                ('medication', models.ForeignKey(help_text='Médicament prescrit.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.medication')),
                ('patient', models.ForeignKey(help_text='Patient concerné par la prescription.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.patient')),
            ],
            options={
                'ordering': ['-start_date', 'id'],
            },
        ),
    ]
